//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=usertele;Password=Metro2018;Connect Timeout=600")]
        public string TeleBancaConnectionString2 {
            get {
                return ((string)(this["TeleBancaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=usertele;Password=Metro2018;Connect Timeout=600")]
        public string TeleBancaConnectionString3 {
            get {
                return ((string)(this["TeleBancaConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=usertele;Password=Metro2018;Connect Timeout=600")]
        public string TeleBancaConnectionString4 {
            get {
                return ((string)(this["TeleBancaConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=usertele;Password=Metro2018;Connect Timeout=600")]
        public string TeleBancaConnectionString {
            get {
                return ((string)(this["TeleBancaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=usertele;Password=Metro2018;Connect Timeout=600")]
        public string TeleBancaConnectionString1 {
            get {
                return ((string)(this["TeleBancaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.22.10;Initial Catalog=TeleBanca;Persist Security Info=True;Us" +
            "er ID=teleban;Password=Metro2018*;Connect Timeout=600")]
        public string TeleBanConnection {
            get {
                return ((string)(this["TeleBanConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.22.3/Service.asmx")]
        public string DataAccessLayer_WSBanco_Service {
            get {
                return ((string)(this["DataAccessLayer_WSBanco_Service"]));
            }
        }
    }
}
