//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.ISWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosBusquedaPersona", Namespace="http://schemas.datacontract.org/2004/07/IdentityService")]
    [System.SerializableAttribute()]
    public partial class DatosBusquedaPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoId {
            get {
                return this.TipoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdField, value) != true)) {
                    this.TipoIdField = value;
                    this.RaisePropertyChanged("TipoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosPersona", Namespace="http://schemas.datacontract.org/2004/07/IdentityService")]
    [System.SerializableAttribute()]
    public partial class DatosPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoId {
            get {
                return this.TipoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoIdField, value) != true)) {
                    this.TipoIdField = value;
                    this.RaisePropertyChanged("TipoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VData", Namespace="http://schemas.datacontract.org/2004/07/IdentityService")]
    [System.SerializableAttribute()]
    public partial class VData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AplicacionActivadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExistePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TarjetaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AplicacionActivada {
            get {
                return this.AplicacionActivadaField;
            }
            set {
                if ((this.AplicacionActivadaField.Equals(value) != true)) {
                    this.AplicacionActivadaField = value;
                    this.RaisePropertyChanged("AplicacionActivada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTarjeta {
            get {
                return this.EstadoTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoTarjetaField, value) != true)) {
                    this.EstadoTarjetaField = value;
                    this.RaisePropertyChanged("EstadoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExistePersona {
            get {
                return this.ExistePersonaField;
            }
            set {
                if ((this.ExistePersonaField.Equals(value) != true)) {
                    this.ExistePersonaField = value;
                    this.RaisePropertyChanged("ExistePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TarjetaId {
            get {
                return this.TarjetaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TarjetaIdField, value) != true)) {
                    this.TarjetaIdField = value;
                    this.RaisePropertyChanged("TarjetaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Data", Namespace="http://schemas.datacontract.org/2004/07/IdentityService")]
    [System.SerializableAttribute()]
    public partial class TB_Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataAccessLayer.ISWS.DatosPersona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TarjetaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTarjeta {
            get {
                return this.EstadoTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoTarjetaField, value) != true)) {
                    this.EstadoTarjetaField = value;
                    this.RaisePropertyChanged("EstadoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataAccessLayer.ISWS.DatosPersona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TarjetaId {
            get {
                return this.TarjetaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TarjetaIdField, value) != true)) {
                    this.TarjetaIdField = value;
                    this.RaisePropertyChanged("TarjetaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISWS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExisteAplicacion", ReplyAction="http://tempuri.org/IService1/ExisteAplicacionResponse")]
        int ExisteAplicacion(string AppName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistraAplicacion", ReplyAction="http://tempuri.org/IService1/RegistraAplicacionResponse")]
        int RegistraAplicacion(string AppName, string URLAct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExistePersona", ReplyAction="http://tempuri.org/IService1/ExistePersonaResponse")]
        bool ExistePersona(DataAccessLayer.ISWS.DatosBusquedaPersona d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreaPersona", ReplyAction="http://tempuri.org/IService1/CreaPersonaResponse")]
        void CreaPersona(DataAccessLayer.ISWS.DatosPersona d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidaPersona", ReplyAction="http://tempuri.org/IService1/ValidaPersonaResponse")]
        DataAccessLayer.ISWS.VData ValidaPersona(DataAccessLayer.ISWS.DatosBusquedaPersona d, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPersona", ReplyAction="http://tempuri.org/IService1/BuscarPersonaResponse")]
        DataAccessLayer.ISWS.DatosPersona BuscarPersona(string TarjetaId, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TB_BuscarPersona", ReplyAction="http://tempuri.org/IService1/TB_BuscarPersonaResponse")]
        DataAccessLayer.ISWS.TB_Data TB_BuscarPersona(string TarjetaId, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CambiaPINTarjeta", ReplyAction="http://tempuri.org/IService1/CambiaPINTarjetaResponse")]
        void CambiaPINTarjeta(string TarjetaId, string PINViejo, string PINNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearTarjeta", ReplyAction="http://tempuri.org/IService1/CrearTarjetaResponse")]
        string CrearTarjeta(DataAccessLayer.ISWS.DatosPersona d, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivarAplicacion", ReplyAction="http://tempuri.org/IService1/ActivarAplicacionResponse")]
        void ActivarAplicacion(string TarjetaId, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReasignarMatriz", ReplyAction="http://tempuri.org/IService1/ReasignarMatrizResponse")]
        bool ReasignarMatriz(DataAccessLayer.ISWS.DatosBusquedaPersona d, string TarjetaId, int AppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReasignarTarjeta", ReplyAction="http://tempuri.org/IService1/ReasignarTarjetaResponse")]
        string ReasignarTarjeta(DataAccessLayer.ISWS.DatosBusquedaPersona d, string TarjetaId_Vieja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidaPINTarjeta", ReplyAction="http://tempuri.org/IService1/ValidaPINTarjetaResponse")]
        bool ValidaPINTarjeta(string TarjetaId, string usrPIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidaPosicPINTarjeta", ReplyAction="http://tempuri.org/IService1/ValidaPosicPINTarjetaResponse")]
        bool ValidaPosicPINTarjeta(string TarjetaId, int[] PINPos, char[] PINDigit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidaRespuesta", ReplyAction="http://tempuri.org/IService1/ValidaRespuestaResponse")]
        bool ValidaRespuesta(string TarjetaId, int fila, int col, string valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DataAccessLayer.ISWS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DataAccessLayer.ISWS.IService1>, DataAccessLayer.ISWS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExisteAplicacion(string AppName) {
            return base.Channel.ExisteAplicacion(AppName);
        }
        
        public int RegistraAplicacion(string AppName, string URLAct) {
            return base.Channel.RegistraAplicacion(AppName, URLAct);
        }
        
        public bool ExistePersona(DataAccessLayer.ISWS.DatosBusquedaPersona d) {
            return base.Channel.ExistePersona(d);
        }
        
        public void CreaPersona(DataAccessLayer.ISWS.DatosPersona d) {
            base.Channel.CreaPersona(d);
        }
        
        public DataAccessLayer.ISWS.VData ValidaPersona(DataAccessLayer.ISWS.DatosBusquedaPersona d, int AppId) {
            return base.Channel.ValidaPersona(d, AppId);
        }
        
        public DataAccessLayer.ISWS.DatosPersona BuscarPersona(string TarjetaId, int AppId) {
            return base.Channel.BuscarPersona(TarjetaId, AppId);
        }
        
        public DataAccessLayer.ISWS.TB_Data TB_BuscarPersona(string TarjetaId, int AppId) {
            return base.Channel.TB_BuscarPersona(TarjetaId, AppId);
        }
        
        public void CambiaPINTarjeta(string TarjetaId, string PINViejo, string PINNuevo) {
            base.Channel.CambiaPINTarjeta(TarjetaId, PINViejo, PINNuevo);
        }
        
        public string CrearTarjeta(DataAccessLayer.ISWS.DatosPersona d, int AppId) {
            return base.Channel.CrearTarjeta(d, AppId);
        }
        
        public void ActivarAplicacion(string TarjetaId, int AppId) {
            base.Channel.ActivarAplicacion(TarjetaId, AppId);
        }
        
        public bool ReasignarMatriz(DataAccessLayer.ISWS.DatosBusquedaPersona d, string TarjetaId, int AppId) {
            return base.Channel.ReasignarMatriz(d, TarjetaId, AppId);
        }
        
        public string ReasignarTarjeta(DataAccessLayer.ISWS.DatosBusquedaPersona d, string TarjetaId_Vieja) {
            return base.Channel.ReasignarTarjeta(d, TarjetaId_Vieja);
        }
        
        public bool ValidaPINTarjeta(string TarjetaId, string usrPIN) {
            return base.Channel.ValidaPINTarjeta(TarjetaId, usrPIN);
        }
        
        public bool ValidaPosicPINTarjeta(string TarjetaId, int[] PINPos, char[] PINDigit) {
            return base.Channel.ValidaPosicPINTarjeta(TarjetaId, PINPos, PINDigit);
        }
        
        public bool ValidaRespuesta(string TarjetaId, int fila, int col, string valor) {
            return base.Channel.ValidaRespuesta(TarjetaId, fila, col, valor);
        }
    }
}
